### PR TITLE
Enhancements and Documentation of the Marketplace Smart Contract

### PR DESCRIPTION
**Pull request by Oladayo-Ahmod**

### CODE REVIEW

**Review by Horlarmmy — APPROVED** [review]
Nice, thanks for the observation

**Comment by Horlarmmy** [comment]
I had to revert the pull, can you include other functions in there?

**Comment by Oladayo-Ahmod** [comment]
sure, no problem.

**Comment by Oladayo-Ahmod** [comment]
i have added it

**Pull request merged**
